### PR TITLE
New gameover screen

### PR DESCRIPTION
**Pull request by KTC96**

### CODE REVIEW

**Review by Koko-66 — CHANGES_REQUESTED** [review]
Could you run a formatter on this, just so we have the file clean? There seems to be an unnecessary space on line 16 and extra line on 3. Sorry for being a bit picky :)

**Review by stephendawsondev — APPROVED** [review]
LGTM!

**Comment by stephendawsondev** [comment]
> Could you run a formatter on this, just so we have the file clean? There seems to be an unnecessary space on line 16 and extra line on 3. Sorry for being a bit picky :)

You should be able to auto-run it by installing the Prettier extension, though you may need to configure it to run on save.

**Review by Koko-66 — APPROVED** [review]
Thanks!

**Pull request merged**
